job_test:
  rules:
    - if: $CI_COMMIT_REF_NAME == "test-upgrade"
  script:
    - cd /home/gitlab-runner/ansible
    - ansible all -m ping
#    - ansible-playbook t_auction_new.yml
  tags:
    - testing

job_deploy:
  rules:
    - if: $CI_COMMIT_REF_NAME == "master" 
  script:
    - cd /home/gitlab-runner/ansible
    - ansible all -m ping
#    - ansible-playbook auction.yml
  tags:
    - testing
